themoment-team/hellogsm-front-25

- apps/client/src/components/FreeGradeForm/index.tsx
- apps/client/src/components/FreeSemesterForm/index.tsx
- apps/client/src/components/TestCalculatePage/index.tsx
- apps/client/src/schemas/scoreForm.ts
- apps/client/src/types/semester.ts
과목 추가, 삭제 과제를 완료하였습니다
자유학년제에서 과목 추가 및 삭제
https://github.com/user-attachments/assets/1fdf575e-69a5-4be3-aca7-4acff7131ce0
자유학기제에서 과목 추가 및 삭제
https://github.com/user-attachments/assets/1d99852f-079f-499b-89ca-c16409596a38
자유학년제에서 과목 추가 입력 후 자유 학기제로 변경한 후 과목 입력
https://github.com/user-attachments/assets/dc6873f9-8279-4109-a5f2-af74bcd71c6c
자유학기제에서 과목 추가 입력 후 자유 학년제로 변경한 후 과목 입력
https://github.com/user-attachments/assets/1d17da15-c0f1-4441-b357-5c9598ff01ff
과목 3개 추가, 전부 입력 후 2번째 과목 제거 -> 1/3번 과목은 유지되는지 확인
https://github.com/user-attachments/assets/71721d5c-9014-4dab-b7dd-e21c2abe7d40
- 삭제, 추가 기능을 구현하였습니다
- scoreFormSchema에 newSubject 필드를 추가하였습니다
추후 useFieldArray 사용법을 익힌후 useFieldArray 사용하여 제작해보겠습니다
> [과제] 과목 추가, 삭제 기능

- apps/client/src/components/MockCalculatePage/index.tsx
- apps/client/src/components/StoryTest/index.stories.tsx
- apps/client/src/components/TestCalculatePage/index.tsx
배포를 하기 위해 build error를 해결하였습니다
- fix buld error
> [build error] 빌드 에러 해결

- apps/client/src/assets/MouseIcon.tsx
- apps/client/src/assets/index.ts
- apps/client/src/components/ConfirmBar/index.stories.tsx
- apps/client/src/components/ConfirmBar/index.tsx
- packages/shared/src/components/ui/Button/index.stories.ts
- packages/shared/src/components/ui/Button/index.tsx
> Confirm Bar를 제작하였습니다.
- Confirm Bar
> [컴포넌트] Confirm Bar 생성

- apps/client/src/assets/CheckIcon.tsx
- apps/client/src/assets/ProgressBar.tsx
- apps/client/src/assets/ProgressBarIcon.tsx
- apps/client/src/assets/index.ts
- apps/client/src/components/StepBar/index.stories.tsx
- apps/client/src/components/StepBar/index.tsx
- packages/api/package.json
- packages/api/tsconfig.json
- packages/types/index.ts
- packages/types/package.json
- pnpm-lock.yaml
> Step Bar를 생성하였습니다.
- Step Bar
https://github.com/user-attachments/assets/8963fb4e-d25f-4144-a59b-843a31059596
디자인에는 애니메이션이 명시되어있지 않았지만 쓰는게 더 좋을 것 같아 사용해 보았습니다.
어떤지 평가 부탁드립니다!
또한, 해당 pr에서 build error 해결하였습니다.
> [컴포넌트] - Step Bar 제작

- apps/client/src/assets/UploadIcon.tsx
- apps/client/src/assets/index.ts
- apps/client/src/components/UploadPhoto/index.stories.tsx
- apps/client/src/components/UploadPhoto/index.tsx
> Upload Photo 컴포넌트 개발
- Upload Photo 컴포넌트
https://github.com/user-attachments/assets/4fdbb8d5-3352-4780-8fce-e6849ad73790
> [컴포넌트] Upload Photo 컴포넌트 개발

- apps/client/src/components/form/ArtPhysicalForm/index.tsx
- apps/client/src/components/form/FreeGradeForm/index.tsx
- apps/client/src/components/form/FreeSemesterForm/index.tsx
- apps/client/src/components/form/NonSubjectForm/index.tsx
- pnpm-lock.yaml
build error를 해결하였습니다
- build error 해결 (react-hook-form의 Controller 사용시 "use client"를 명시해줘야 하는 에러였습니다)
> [build error] 빌드에러 해결

- apps/admin/src/components/ApplicantTH/index.tsx
- apps/admin/src/components/ApplicantTR/index.tsx
- apps/admin/src/components/FilterBar/index.tsx
- apps/admin/src/components/SideMenu/index.tsx
- apps/admin/src/pageContainer/MainPage/index.tsx
- apps/admin/src/pageContainer/TicketPage/index.tsx
- packages/shared/src/components/ui/Pagination/index.tsx
> 이 pr의 목적을 적어주세요
- 잘못 잡혀있던 스타일들을 수정했습니다. -> 페이지네이션, overflow, bg
- tool tip을 추가했습니다.
- 실물원서제출여부 변경 시 alert dialog를 추가했습니다.
> fix: admin 스타일 수정, dialog 추가

- apps/client/src/components/Header/index.tsx
> [Fix] 마이페이지로 이동하는 링크 수정

- packages/shared/src/components/UploadPhoto/index.tsx
- packages/shared/src/components/register/BasicRegister/index.tsx
> step img 초기화 처리
- step img를 초기화되지 않게 하였습니다.
- address를 disabled로 전환하였습니다.
> [QA] img 초기화

- apps/admin/src/app/apis/oneseo/getAdmissionTickets.ts
- apps/admin/src/app/apis/oneseo/getMyAuthInfo.ts
- apps/admin/src/app/apis/oneseo/getOneseoById.ts
- packages/api/src/hooks/api/oneseo/usePostTempStorage.ts
- packages/api/src/libs/requestUrlController.ts
- packages/shared/src/components/ConfirmBar/index.tsx
- packages/shared/src/components/ScoreRegister/index.tsx
- packages/shared/src/components/StepBar/index.tsx
- packages/shared/src/components/StepsContainer/index.tsx
- packages/shared/src/components/form/FreeSemesterForm/index.tsx
- packages/shared/src/stores/store.ts
step4가 아닌 곳에서 step4의 내용 임시저장, step4 -> step3 -> step4로 이동시 값 초기화 문제를 해결하였습니다
- postTempStorage query 추가
- 전역 상태 필드 추가
- scoreRegister, stepsContainer 수정
> [QA] step4가 아닌 곳에서 step4의 내용 임시저장, step4 -> step3 -> step4로 이동시 값 초기화 문제

- apps/client/src/pageContainer/SignUpPage/index.tsx
- packages/shared/src/components/ui/Select/index.tsx
회원가입페이지 레이아웃 shift 현상 해결하였습니다
- style 수정
> [QA] 회원가입페이지 레이아웃 shift 현상 해결

- apps/admin/next.config.mjs
- apps/admin/src/app/edit/[memberId]/page.tsx
- apps/admin/src/components/ApplicantTR/index.tsx
- apps/admin/src/pageContainer/TicketPage/index.tsx
- apps/client/next.config.mjs
- packages/shared/src/components/ScoreRegister/index.tsx
- packages/shared/src/components/UploadPhoto/index.tsx
- pnpm-lock.yaml
어드민 페이지를 수정하였습니다
- next.config.mjs remotePatterns 추가
- 원서 수정 로직 수정
> [QA] 어드민 페이지 수정

- apps/client/src/assets/FooterGSMLogo.tsx
- apps/client/src/components/Footer/index.tsx
- apps/client/src/pageContainer/GuidePage/index.tsx
- packages/shared/src/components/UploadPhoto/index.tsx
- packages/tailwind-config/tailwind.config.ts
guide page, footer 반응형 작업하였습니다
- guide page, footer 반응형
> [QA] guide page, footer 반응형

- packages/shared/src/components/StepsContainer/index.tsx
screening, major 임시저장 문제 해결
- screening 임시저장 문제 해결
- major 임시저장 문제 해결
문제 발생 이유가 조건식에 있어 새로운 switch case 조건문을 만들었습니다.
> [QA] screening, major 임시저장 문제 해결

- packages/shared/src/components/ScoreRegister/index.tsx
원서를 작성하고 특정 상황에서 제출이 안되는 상황을 해결하였습니다
- 1_2 setValue 추가
> [QA] 원서 제출안됨 수정

- apps/admin/src/components/ApplicantTH/index.tsx
- apps/admin/src/components/ApplicantTR/index.stories.tsx
- apps/admin/src/components/ApplicantTR/index.tsx
- apps/client/src/pageContainer/GuidePage/index.tsx
- packages/api/src/hooks/api/oneseo/index.ts
- packages/api/src/hooks/api/oneseo/usePatchAgreeDocStatus.ts
- packages/api/src/libs/queryKeys.ts
- packages/api/src/libs/requestUrlController.ts
- packages/shared/src/components/StepsContainer/index.tsx
- packages/types/src/oneseo.ts
입학 동의서 제출 여부 토글을 개발하였습니다.
- 입학 동의서 제출 여부 토글 제작
- usePathAgreeDocStatus 제작
- guide page button 조건식 수정
현재 최종합격한 지원자의 원서만 변경할 수 있기 때문에 400이 뜨는 것이 정상입니다.
> [QA] 입학동의서 제출 여부 개발

- apps/admin/src/pageContainer/TicketPage/index.tsx
- apps/client/src/components/OneseoStatus/index.tsx
- apps/client/src/pageContainer/PrintPage/index.tsx
- packages/shared/src/components/ScoreRegister/index.tsx
- packages/shared/src/components/StepBar/index.tsx
- packages/shared/src/components/StepsContainer/index.tsx
- packages/shared/src/components/register/GuardianRegister/index.tsx
- packages/shared/src/schemas/basicRegisterSchema.ts
- packages/types/src/oneseo.ts
원서 제출 서류 수정, 원서 작성 필드를 수정하였습니다
- getMyOneseoType 수정
- basicRegisterSchema 수정
- 원서 제출 서류 값 수정
- 원서 작성시 담임 선생님 이름, 전화번호 조건부로 변경
> [QA] 원서 제출 서류 수정, 원서 작성 필드 수정

- apps/client/src/components/Footer/index.tsx
- apps/client/src/pageContainer/GuidePage/index.tsx
guide 페이지 반응형 화면을 수정하였습니다
- guide 페이지 반응형 화면 수정
> [QA] guide 페이지 반응형 수정

- apps/admin/src/app/layout.tsx
- apps/client/src/app/layout.tsx
- apps/storybook/.storybook/preview-head.html
- packages/shared/src/styles/globals.css
프로젝트에 pretendard 적용시켰습니다
- font 적용
> [QA] pretendard font 적용

- apps/client/src/app/mypage/page.tsx
- apps/client/src/app/print/page.tsx
- apps/client/src/app/register/page.tsx
- apps/client/src/app/signup/page.tsx
- apps/client/src/components/Header/index.tsx
- apps/client/src/components/LoginDialog/index.tsx
- apps/client/src/components/MainPage/Section2/index.tsx
- apps/client/src/components/MainPage/Section4/index.tsx
- apps/client/src/pageContainer/GuidePage/index.tsx
임시적으로 redirect를 적용시켰습니다.
- 임시 redirect 및 주석처리
> [QA] 빠른 상용배포를 위해 임시로 로그인이 필요한 페이지 redirect 처리

- packages/shared/src/components/EditBar/index.tsx
- packages/shared/src/components/ScoreRegister/index.tsx
- packages/shared/src/components/StepsContainer/index.tsx
edit bar의 원서 수정하기 버튼을 step 4에서만 보이게 변경했습니다
- edit bar 수정
> [QA] edit bar 수정

- apps/client/src/assets/ChevronIcon.tsx
- apps/client/src/assets/Star2Icon.tsx
- apps/client/src/assets/Star3Icon.tsx
- apps/client/src/assets/StarIcon.tsx
- apps/client/src/components/FaqElement/index.tsx
- apps/client/src/components/Header/index.tsx
- apps/client/src/components/MainPage/Section1/index.tsx
- apps/client/src/components/MainPage/Section2/index.tsx
- apps/client/src/components/MainPage/Section3/index.tsx
- apps/client/src/components/MainPage/Section4/index.tsx
- apps/client/src/components/MainPage/Section5/index.tsx
- apps/client/src/pageContainer/FaqPage/index.tsx
- apps/client/src/pageContainer/GuidePage/index.tsx
- apps/client/src/pageContainer/MyPage/index.tsx
- apps/client/tailwind.config.ts
tailwind.config.ts를 커스텀 하여 커스텀 px로 변경
- tailwind.config.ts 커스텀 변경
- main page section별 반응형
- guide page 반응형
- faq page 반응형
- main page console.log 에러 문제 해결
- header logo 클릭시 홈으로 이동 기능 생성
> [QA] 페이지 별 반응형

- apps/client/src/components/OneseoStatus/index.tsx
- apps/client/src/constants/date.ts
- apps/client/src/pageContainer/GuidePage/index.tsx
- apps/client/src/pageContainer/PrintPage/index.tsx
- packages/shared/src/constants/date.ts
- packages/shared/src/styles/globals.css
원서 제출 서류, 가이드 페이지, 날짜를 수정 하였습니다
- 날짜 수정
- 제출 서류, 프린트 수정
- guide 페이지 수정
> [QA] 원서 제출 서류, 가이드 페이지, 날짜 수정

- packages/shared/src/components/ScoreRegister/index.tsx
점수 입력폼 기본값 수정
- null일떄 기본값을 0으로 주도록 변경하였습니다
> [QA] 기본값 수정

- apps/admin/src/components/ApplicantTR/index.stories.tsx
- apps/admin/src/components/ApplicantTR/index.tsx
- apps/admin/src/pageContainer/MainPage/index.tsx
- packages/api/src/hooks/api/oneseo/index.ts
- packages/api/src/hooks/api/oneseo/useGetEditability.ts
- packages/api/src/libs/queryKeys.ts
- packages/api/src/libs/requestUrlController.ts
- packages/types/src/oneseo.ts
원서 수정 가능 여부 기능을 제작하였습니다
- useGetEditability 제작
- 필요없는 console.log 삭제
> [admin] 원서 수정 가능 여부 기능 제작

- apps/admin/src/app/layout.tsx
- apps/admin/src/components/ApplicantTR/index.tsx
- apps/client/src/app/guide/page.tsx
- apps/client/src/app/layout.tsx
- apps/client/src/app/mypage/page.tsx
- apps/client/src/app/print/page.tsx
- apps/client/src/app/register/page.tsx
- apps/client/src/pageContainer/GuidePage/index.tsx
- apps/client/src/pageContainer/MyPage/index.tsx
- packages/api/src/apis/date/getDate.ts
- packages/api/src/apis/date/index.ts
- packages/api/src/apis/index.ts
- packages/api/src/index.ts
- packages/api/src/libs/requestUrlController.ts
- packages/shared/src/components/ScoreRegister/index.tsx
- packages/types/src/date.ts
- packages/types/src/index.ts
date api 연결, 자유학기제 이슈 해결
- getDate 함수 추가
- 기간에 따른 렌더링, 리다이렉트 추가
> [QA] date api 연결, 자유학기제 이슈 해결

- apps/admin/src/components/ApplicantTH/index.tsx
- apps/admin/src/components/ApplicantTR/index.tsx
- apps/client/src/components/Header/index.tsx
admin 페이지 px을 수정하였습니다.
- px을 rem으로 수정
- 1770px
- 1920px
> [QA] admin px 수정

- packages/shared/src/components/ScoreRegister/index.tsx
react-hook-form 기본값 조건식 수정
- 조건식 수정
> [QA] 기본값 조건식 수정

- apps/admin/src/components/ApplicantTR/index.tsx
- packages/shared/src/components/register/BasicRegister/index.tsx
- packages/shared/src/components/ui/Pagination/index.tsx
원서 수정 불가 시 모달 추가
- 새롭게 디자인에 추가된 원서 수정이 불가 시 (oneseoEditability 가 false일 경우)의 모달을 제작하였습니다.
- 주소지의 zoneCode를 삭제하였습니다.
> [QA] 원서 수정 불가 시 모달 추가

- apps/client/src/components/PassResultDialog/index.tsx
- packages/types/src/member.ts
합격 발표 모달에 지원 학과 표시
새로 추가된 api 스펙에 맞게 모달을 변경하였습니다.
> [QA] decide major modal 추가

- apps/client/src/components/Header/index.tsx
- apps/client/src/components/TeamPage/TeamSection2/index.tsx
- apps/client/src/components/TeamPage/TeamSection3/index.tsx
- apps/client/src/components/TeamPage/TeamSection4/index.tsx
더모먼트 팀 페이지 반응형 추가
새로 추가된 디자인에 맞춰 더모먼트 팀 페이지 반응형을 추가하였습니다.
> [QA] team page 반응형

- apps/admin/src/components/FilterBar/index.tsx
- apps/client/src/pageContainer/MyPage/index.tsx
- packages/shared/src/components/StepBar/index.tsx
- packages/shared/src/components/StepsContainer/index.tsx
- packages/shared/src/components/register/ApplyRegister/index.tsx
전형 선택하는 사항들을 변경하였습니다
- 기존 정원 외 특별전형에서 국가보훈대상자, 특례입학대상자로 변경하였습니다.
- admin 에서 기존에 없었던 정원 외 특별전형 선택지를 생성하였습니다.
> [QA] 전형 선택 사항 업데이트

- apps/client/src/components/OneseoStatus/index.tsx
- apps/client/src/components/PassResultDialog/index.tsx
- apps/client/src/pageContainer/PrintPage/index.tsx
- packages/shared/src/components/ConfirmBar/index.tsx
- packages/shared/src/components/ScoreRegister/index.tsx
- packages/shared/src/components/StepBar/index.tsx
- packages/shared/src/components/StepsContainer/index.tsx
- packages/types/src/member.ts
- packages/types/src/oneseo.ts
팀 내부 테스트 이슈 수정
- 원서 작성중 새고로침에 대한 핸들링 수정
- 검정고시일때 성적 계산하기 제대로 안되는 문제 수정
- 합격 모달에서 학과가 보이지 않는 문제 수정
- 제출 서류 예체능 성적 부분 수정
- 원서 접수번호 수정
> [QA] 팀 내부 테스트 이슈 수정

- apps/client/src/components/TeamPage/TeamSection2/index.tsx
- apps/client/src/components/TeamPage/TeamSection4/index.tsx
더모먼트 페이지 반응형 수정
- 더모먼트 페이지 반응형 issue를 수정하였습니다
-
> [QA] 더모먼트 페이지 반응형 수정

- apps/client/src/app/provider.tsx
- apps/client/src/pageContainer/PrintPage/index.tsx
- package.json
- packages/shared/src/assets/icon/Toast/CloseIcon.tsx
- packages/shared/src/assets/icon/Toast/InfoIcon.tsx
- packages/shared/src/assets/index.ts
- packages/shared/src/components/ConfirmBar/index.tsx
- packages/shared/src/components/ScoreRegister/index.tsx
- packages/shared/src/components/StepsContainer/index.tsx
- packages/shared/src/components/form/ArtPhysicalForm/index.tsx
- packages/shared/src/styles/globals.css
- packages/types/src/oneseo.ts
- pnpm-lock.yaml
상용 테스트 이슈 수정
- 임시저장 시 모달 보여짐 -> 토스트로 변경
- 자유학기제 일시 예체능 입력도 자유학기제인 학기를 제외하고 입력하도록 수정
- 전형 성적 확인서 수정
- 성적 입력 임시지정시 포함 안되는 문제 수정
- 전형성적 입력 확인서 노출 조건식 수정
> [QA] 상용 테스트 이슈 수정

- apps/client/src/pageContainer/SignUpPage/index.tsx
전화번호 코드가 만료되었을 경우의 로직을 제작하였습니다.
전화번호 코드가 만료되었을 경우의 로직 생성
> [QA] 전화번호 코드 만료 로직 제작

- apps/client/src/pageContainer/PrintPage/index.tsx
- packages/shared/src/components/ScoreRegister/index.tsx
전형성적 확인서 수정, 원서 수정 로직 수정
- 전형성적 확인서 수정
- 원서 수정 로직 수정
> [QA] 전형성적 확인서 수정, 원서 수정 로직 수정

- apps/admin/src/components/ApplicantTR/index.tsx
- apps/admin/src/pageContainer/MainPage/index.tsx
- apps/client/src/pageContainer/PrintPage/index.tsx
상용 테스트에서 생긴 어드민 기능 이슈를 해결하였습니다
- user list 필터 조건 변경시 page를 처음으로 set하는 로직을 추가하였습니다
- 직무적성점수, 심층면접점수 가드를 추가하였습니다
- 검정고시일시 return 추가
> [QA] 어드민 이슈 해결

- packages/shared/src/components/StepsContainer/index.tsx
임시저장시 Image set 추가
-  임시저장시 Image set 추가
> [QA] 임시저장시 Image set 추가

- apps/client/src/components/MainPage/Section2/index.tsx
- apps/client/src/components/TeamPage/TeamSection1/index.tsx
- apps/client/src/pageContainer/MyPage/index.tsx
- apps/client/tailwind.config.ts
section 2의 반응형 issue를 수정하였습니다.
- section 2 반응형 issue 수정
- my page 반응형 수정
> [hotfix] section 2 반응형 수정

- apps/client/src/app/layout.tsx
- apps/client/src/lib/GoogleAnalytics.tsx
- apps/client/src/lib/index.ts
Google Analytics 설정을 하였습니다.
- GA 설정
> Google Analytics 설정

- apps/client/src/app/layout.tsx
stage 환경을 검색엔진에 제외 시켰습니다
- env 값이 stage라면 meta 태그 추가
> [SEO] stage 환경 검색엔진 제외

- apps/client/src/app/guide/page.tsx
> hotfix: date

- apps/client/src/pageContainer/PrintPage/index.tsx
> 이 pr의 목적을 적어주세요
> 이 pr에서 작업한 내용을 적어주세요
> 관련된 issue를 적어주세요(없다면 이 부분은 삭제 해주세요)
> fix : 잘못된 인덱스 접근 수정

- packages/shared/src/components/StepsContainer/index.tsx
언마운트시 setAll 추가
- 언마운트시 setAll 추가
> [hotfix] 언마운트시 setAll 추가

- packages/shared/src/components/ConfirmBar/index.tsx
- packages/shared/src/components/EditBar/index.tsx
- packages/shared/src/components/ScoreRegister/index.tsx
- packages/shared/src/components/StepsContainer/index.tsx
연속 클릭 작동을 방지하도록 수정하였습니다
- 클릭했을때 동작이 다 실행 전까지 버튼 비활성화
> [hotfix] 연속 클릭 방지

- packages/shared/src/components/EditBar/index.tsx
admin 수정 페이지에 홈 버튼을 추가하였습니다.
admin home button 추가
> [hotfix] admin home button 추가

- apps/admin/src/components/FilterBar/index.tsx
admin api 요청 확인 모달 추가
admin api 요청 확인 모달을 추가하였습니다.
> [hotfix] admin 확인 모달 추가

- apps/client/src/pageContainer/SignUpPage/index.tsx
timer 세로고침 초기화 이슈 해결
timer 세로고침 시 초기화 이슈를 해결하였습니다 (session storage를 사용하였습니다)
> [hotfix] timer 세로고침 시 초기화 이슈 해결

- apps/admin/src/pageContainer/TicketPage/index.tsx
- packages/shared/src/constants/date.ts
- packages/types/src/oneseo.ts
ticket page 날짜와 필드를 수정하였습니다.
ticket page 날짜와 필드를 수정
> [hotfix] ticket page 수정

- apps/client/src/app/apis/oneseo/getMyOneseo.ts
- apps/client/src/pageContainer/MainPage/index.tsx
> server side fetching error로 인한 원서 접수 페이지 접속 에러 해결
1. getMyOneseo - server side fetching try/catch 에러 핸들링 추가
2. Mainpage - 로그인 alert 다음에 클릭 시, 최하단으로 스크롤 되는 현상 해결
> [fix] server side fetching error로 인한 원서 접수 페이지 접속 에러 해결

- apps/client/src/app/layout.tsx
- apps/client/src/app/page.tsx
- apps/client/src/app/provider.tsx
- apps/client/src/components/Header/index.stories.ts
- apps/client/src/components/Header/index.tsx
- apps/client/src/components/MainPage/Section3/index.tsx
- apps/client/src/pageContainer/MainPage/index.tsx
- apps/client/src/utils/getIsServerHealthy.ts
- apps/client/src/utils/index.ts
서버가 비활성 상태일때 서버를 사용하는 페이지 링크를 감추는 작업을 하였습니다
- 서버 상태에 따른 렌더링 추가
- 환경변수 추가
> [hotfix]서버 상태에 따른 렌더링

- apps/admin/src/components/ApplicantTH/index.tsx
- packages/shared/src/stores/store.ts
- packages/shared/src/utils/dataUrltoFile.ts
오타를 수정합니다.
- 오타 수정
- Nmae -> Name
- splited -> split
> Fix minor typos

- apps/admin/src/app/page.tsx
- apps/admin/src/components/ApplicantTH/index.tsx
- apps/client/src/app/apis/oneseo/getMyOneseo.ts
- apps/client/src/assets/HamburgerIcon.tsx
- apps/client/src/assets/NotFoundZeroIcon.tsx
- apps/client/src/assets/SparkleIcon.tsx
- apps/client/src/assets/index.ts
- apps/client/src/components/Header/index.tsx
- apps/client/src/pageContainer/NotFoundPage/index.tsx
- packages/code-style-config/eslint/cspell.config.yaml
- packages/code-style-config/eslint/index.js
- packages/code-style-config/package.json
- pnpm-lock.yaml
eslint spell checker 플러그인을 적용하고 오타를 수정하였습니다 
- 오타 수정
- 플러그인 세팅 (eslint 플러그인으로 추가함으로 오타가 있다면 빌드시 에러를 띄우기 때문에 오타를 검수할수 있을것 같습니다)
> [feat] @cspell/eslint-plugin eslint 세팅

- apps/client/src/components/LoginNoticeDialog/index.tsx
- apps/client/src/components/index.ts
- apps/client/src/pageContainer/MainPage/index.tsx
메인페이지에 뜨는 모달을 비활성화 하였습니다.
메인페이지 모달 주석처리
> [fix] 메인페이지에 뜨는 모달 비활성화

- apps/client/src/components/MainPage/Section3/index.tsx
> section3의 원서접수 바로가기 버튼클릭시 "/"으로 이동됨
> 리다이렉트 URL을 "/" 에서 "/guide"로 수정
> [hotfix] : section3 원서접수 바로가기 Redirect URL 변경

- apps/client/src/components/Header/index.tsx
잘못된 조건식으로 인한 스타일 오류를 해결하였습니다
변경전
변경후
- 조건식 위치 수정
> [hotfix] : header 스타일 수정

- apps/admin/src/lib/utils.ts
- apps/client/src/app/provider.tsx
- apps/client/src/components/ActiveLink/index.tsx
- apps/client/src/components/Header/index.tsx
- apps/client/src/components/MainPage/Section2/index.tsx
- apps/client/src/components/MainPage/Section3/index.tsx
- apps/client/src/lib/utils.ts
- apps/client/src/pageContainer/PrintPage/index.tsx
> [deploy] 정기 배포

- .github/workflows/regular-deploy.yml
정기베포를 자동화하는 github action
정기베포를 자동화하는 github action을 작업했습니다
활성화 일시 기준 14일이 지날때 마다 0시에 develop에서 main으로 가는 PR이 생성됩니다
테스트 예시
> [feat] 정기베포 자동화

- .github/workflows/prod-ci.yml
- .github/workflows/stage-ci.yml
CI 작동시 pnpm build 명령어를 추가하여 모든 패키지의 build, lint 검사를 하도록 작성하였습니다
- CI rule 수정
> [fix] CI Rule 수정

- .github/workflows/prod-cd.yml
- .github/workflows/stage-cd.yml
CD Flow에 사용하지 않는 이미지를 삭제하는 명령어를 추가하였습니다
- 삭제 명령어 추가
> [fix] : CD 작동중 사용하지 않는 이미지 삭제 명령어 추가

- .github/workflows/prod-cd.yml
- .github/workflows/prod-ci.yml
- .github/workflows/stage-cd.yml
- .github/workflows/stage-ci.yml
OAuth를 위한 환경 변수 추가했습니다.
- OAuth 환경 변수 추가
- repository secrets 값 추가
> [ci] oauth 환경 변수 추가

- apps/client/src/app/page.tsx
관리자 페이지 리디렉션 시 호스트 감지 로직 수정했습니다.
- 관리자 페이지 리디렉션 시 호스트 감지 로직 수정
> [fix] 관리자 페이지 리디렉션 시 호스트 감지 로직 수정

- apps/client/src/pageContainer/SignUpPage/index.tsx
개인정보 동의 토글 스크롤 제거
토글시에 보이는 부분에 스크롤을 제거했습니다
before
after
> [fix] 개인정보 동의 토글 스크롤 제거

- apps/client/src/pageContainer/MyPage/index.tsx
> [style] 변경된 mypage 아이콘, 문구 수정 

- apps/client/src/components/Header/index.tsx
- apps/client/src/components/MainPage/Section1/index.tsx
- apps/client/src/components/MainPage/Section3/index.tsx
- apps/client/src/pageContainer/GuidePage/index.tsx
- apps/client/src/pageContainer/SignUpPage/index.tsx
- packages/shared/src/components/register/Step2Register/index.tsx
> 맞춤법과 띄어쓰기 검토를 진행했습니다.
- 일반 문장 맞춤법 및 띄어쓰기 수정
- 예) "할 수 없는" 
- 학교명, 과명, 바로가기 등 **기존과 동일하게 유지** 
(+기타)
작업하는 과정에서 발견한 불필요한 주석 제거도 했습니다.
> [fix] 맞춤법 및 띄어쓰기 

- apps/client/src/pageContainer/CheckResultPage/index.tsx
> 합격자 조회 페이지 반응형 추가 완료했습니다
**[변경 전]**
**[변경 후]**
> [style] 합격자 조회 페이지 반응형

- apps/client/src/components/PrintPage/ApplicationPledge/index.tsx
- apps/client/src/components/PrintPage/ScoreConfirmationForm/index.tsx
> 학교장 직인 표시를 `oneseo` 데이터로 동적으로 변경하였습니다
> [feat:] 학교장 직인 자동 표시

- apps/client/src/components/PrintPage/ApplicationPledge/index.tsx
> `printPage` 이중지원 관련 문구 수정 작업 완료했습니다.
> [fix] 이중지원 관련 문구 수정

- packages/shared/src/components/UploadPhoto/index.tsx
업로드 가능한 증명사진 형식 안내 추가 했습니다.
- 업로드 가능한 증명사진 형식 안내 추가
> [feat] 증명사진 업로드 형식 안내 추가

- apps/admin/src/components/FilterBar/index.tsx
- packages/shared/src/components/register/Step3Register/index.tsx
선생님 요구사항대로 '연락처'를 '휴대폰 번호'로 수정했습니다
- '연락처'를 '휴대폰 번호'로 수정
> [feat] '연락처'를 '휴대폰 번호'로 수정

- apps/client/src/pageContainer/SignUpPage/index.tsx
- packages/shared/src/components/register/Step3Register/index.tsx
step3와 signup페이지에서 하이픈 제외 문구를 추가 했습니다
> [feat] 하이픈 제외 문구 추가

- apps/client/src/components/PrintPage/PersonalInfoTable/index.tsx
> https://github.com/themoment-team/hellogsm-front-25/pull/296 해당 pr에서 `cn` 함수 적용을 할 때 놓친 오류 수정했습니다.
> [fix] 성별 칸 className cn 함수 적용 오류 수정

- packages/shared/src/components/modal/ClientModals/index.tsx
https://github.com/themoment-team/hellogsm-front-25/pull/283 해당 pr에서 문제가 해결되지 않았어서 window.location.replace를 사용하는 방식으로 변경했습니다.
- Link 태그를 사용하는 대신에 window.location.replace를 사용하는 방식으로 변경
> [fix] 회원가입 성공 후 리다이렉트 로직 수정

- apps/client/src/app/callback/page.tsx
next.js의 redirect() 함수는 예외를 throw하는 방식으로 동작한다고 합니다. 따라서 try-catch 블록 안에서는 사용하면 안 되며, 이 때문에 해당 코드를 제거했습니다.
- 콜백 페이지 내 불필요한 try-catch 제거
> [fix] 콜백 페이지 내 불필요한 try-catch 제거

- .github/workflows/prod-cd.yml
- .github/workflows/prod-ci.yml
- .github/workflows/regular-deploy.yml
- .github/workflows/reusable-build.yml
- .github/workflows/reusable-deploy.yml
- .github/workflows/reusable-notifications.yml
- .github/workflows/stage-cd.yml
- .github/workflows/stage-ci.yml
> GitHub Actions 워크플로우 **최적화** 및 **배포 안정성 개선**
* 5개 워크플로우에서 동일한 빌드/배포/알림 로직 **중복 발생**
* 환경별 설정 변경 시 **여러 파일 수정 필요 → 유지보수성 저하**
* 새로운 환경(dev, staging 등) 추가 시 **전체 워크플로우 복사 필요**
* Blue-Green 배포 로직 및 Docker 빌드 로직이 **여러 파일에서 반복**
* `reusable-build.yml`: 빌드, Docker 이미지 생성, ECR 푸시
* `reusable-deploy.yml`: 단순/Blue-Green 배포
* `reusable-notifications.yml`: Discord 알림 통합
- `hello-gsm-prod-ci/cd`, `hello-gsm-stage-ci/cd` 등에서
→ **입력값(environment, ports, secrets)만 전달**
- PR 워크플로우(`regular deploy PR creation`)에서도 **알림 재사용**
- Blue-Green 배포 시 **포트/색상 자동 선택 로직 통합**
- Docker 빌드 시 `.env.client`, `.env.admin` **자동 생성**
* **유지보수성 향상**: 환경별 워크플로우 복사/수정 불필요
* **코드 중복 \~70% 감소**: 빌드/배포/알림 로직 중앙 집중화
* **배포 안정성 강화**: Blue-Green 배포 로직 재사용으로 다운타임 최소화
* **알림 일원화**: CI/CD 성공/실패 알림 형식 통일
(참고) …
> [refactor] GitHub Actions 워크플로우 최적화 및 SSH 배포 안정성 개선

- apps/client/src/components/Header/index.tsx
> 로그인 상태일 경우(**사용자 입장**: **회원가입 진행 중**) 헤더에 불필요한 Navigation UI를 제거하였습니다.
> [fix] 로그인 상태일 경우 Navigation UI 제거

- apps/admin/src/pageContainer/TicketPage/index.tsx
>  Admin PrintPage 안내 문구를 '직접 방문' -> '방문 제출' 로 변경하였습니다.
> [fix] Admin PrintPage 안내문구 수정
