apps/admin/src/app/page.tsx, apps/admin/src/components/ApplicantTH/index.tsx, apps/admin/src/components/ApplicantTR/index.tsx, apps/admin/src/components/FilterBar/index.tsx, apps/admin/src/components/SideMenu/index.tsx, apps/admin/src/components/index.ts, apps/admin/src/pageContainer/MainPage/index.tsx, apps/admin/src/pageContainer/index.ts, apps/admin/tsconfig.json, packages/shared/src/components/index.ts, packages/shared/src/components/ui/Pagination/index.stories.tsx, packages/shared/src/components/ui/Pagination/index.tsx, packages/types/src/oneseo.ts
> admin의 메인 페이지를 조립 및, 구성했습니다.
- 각 컴포넌트의 스타일을 전체 페이지 구성에 맞게 일부 변경했습니다.
// TODO
- API 스펙에 맞는 application 타입 선언과, 페이지네이션 구성이 필요합니다.
=> [Admin] admin 메인 페이지 구성

apps/client/src/app/apis/member/getMyAuthInfo.ts, apps/client/src/app/apis/member/getMyMemberInfo.ts, apps/client/src/app/page.tsx, apps/client/src/components/Header/index.tsx
> 로그인 시 유저 정보가 업다면 회원가입으로 이동되도록 하였습니다.
- 회원가입 페이지에도 헤더가 존재하여, 잘못된 유저 정보가 표시되었습니다. 이를 예외처리 했습니다.
=> [Member] 로그인 시 유저 정보가 없다면 회원가입으로 이동.

apps/client/src/pageContainer/PrintPage/index.tsx, apps/client/src/pageContainer/SignUpPage/index.tsx, packages/shared/src/components/ScoreRegister/index.tsx
회원가입시 refetch 추가, freeSemester null 로직을 변경하였습니다
- 회원가입 성공시 refetch를 실행해 회원 정보를 다시 가져옵니다
- freeSemester null 로직을 변경해 다른 학기를 on 할시 전 학기의 placeholder가 제대로 보입니다
- `/print` tr background-image -> img src로 변경
=> [QA] 회원가입시 refetch 추가, freeSemester null 로직을 변경

apps/client/src/components/MainPage/Section5/index.tsx, apps/client/tailwind.config.ts
section5 반응형 수정했습니다
- viewport width 1117px 이하에서 세로로 나열되던 카드들이 viewport width 982px ~ 1023px 구간에서 갑작스럽게 가로로 2, 1 배치가 되는 현상 해결
- viewport width가 600px 밑으로 내려가면 카드들이 가로로 배치되며 가로스크롤 되도록 변경
https://github.com/user-attachments/assets/504ea1bd-5a9e-4cb7-8ee8-932605e49ad2
https://github.com/user-attachments/assets/a18a4632-9973-4c3d-9ba8-7a356a63d629
=> [hotfix] section5 반응형 수정

apps/client/src/app/faq/page.tsx, apps/client/src/components/MainPage/Section3/index.tsx, apps/client/src/pageContainer/FaqPage/index.tsx
> "바로가기" 버튼 클릭 시 드롭다운이 나타나도록 수정했습니다.
여러 계정으로 로그인하는 방법을 더욱 쉽게 안내하기 위해, **"바로가기" 버튼 클릭 시 드롭다운이 활성화되도록 수정**했습니다.
**기존:**
- "바로가기" 버튼 클릭 시 FAQ 페이지로 이동했으나, 동작이 직관적이지 않아 사용자가 쉽게 인지하기 어려웠음.
**변경:**
- "바로가기" 버튼 클릭 시 로그인 방법을 안내하는 **드롭다운이 나타나도록 기능 추가**
- 사용자가 보다 직관적으로 여러 계정 로그인 방법을 확인할 수 있도록 개선
- 드롭다운을 닫았을 때 URL에서 openIndex 파라미터가 제거되도록 수정
https://github.com/user-attachments/assets/c6358ae0-102f-4c09-9319-b8a7ce7b06d2
1. 홈 페이지로 이동
2. 스크롤을 내려 **"광주소프트웨어마이스터고등학교 2025 신입생 모집"** 섹션으로 이동
3. **"여러 계정으로 로그인하는 방법 🚦"** 영역에서 **"바로가기" 버튼을 클릭**
4. 여러 계정 로그인 방법을 안내하는 **드롭다운이 정상적으로 나타나는지 확인**
5. 여러 계정 로그인 방법 드롭다운을 닫았을 때, URL에서 openIndex 파라미터가 제거되는지 확인
=> [fix]: 로그인 방법 바로가기 버튼 클릭 시 드롭다운 활성화

apps/admin/src/lib/utils.ts, apps/client/src/app/provider.tsx, apps/client/src/components/ActiveLink/index.tsx, apps/client/src/components/Header/index.tsx, apps/client/src/components/MainPage/Section2/index.tsx, apps/client/src/components/MainPage/Section3/index.tsx, apps/client/src/lib/utils.ts, apps/client/src/pageContainer/PrintPage/index.tsx
`cn` 유틸 함수 임포트를 `shared` 경로로 통합하여 코드 일관성과 재사용성을 높였습니다
- `apps/client/src/lib/utils.ts` 파일 삭제
- `apps/admin/src/lib/utils.ts` 파일 삭제
- `cn` 유틸 함수를 `client` 경로에서 임포트하던 몇몇의 코드들을 `shared` 경로에서 임포트 하도록 변경
- github에서 폴더가 사라지지 않도록 `apps/admin/src/lib/.gitkeep` 파일 추가
`apps/client/src/pageContainer/PrintPage/index.tsx` 에서 `cn` 유틸 함수를 사용하지 않고 스타일을 적용시키고 있음
=> [refactor] client/admin의 cn 유틸 제거 및 shared 경로로 통일

apps/client/src/pageContainer/FaqPage/index.tsx
> FAQ 페이지네이션 및 질문 열기 시 스크롤 이동 버그 수정했습니다.
- 페이지네이션 처리 시 각 항목에 전역 인덱스(globalIndex)를 사용하여 페이지 간 중복 문제 해결
- 질문 클릭 시 페이지가 상단으로 스크롤되는 문제를 `router.replace(..., { scroll: false })`로 방지
https://github.com/user-attachments/assets/ca4046f4-0722-487e-8daf-2c9017920e4a
openIndex값을 확인해주세요!
https://github.com/user-attachments/assets/dac21c01-a468-48b2-97d5-e2e53b65b596
openIndex값을 확인해주세요!
`develop`을 삭제해야하는 상황이 발생하여, 
`develop`을 삭제 하고 다시 생성하는 과정에서 이전 pr이 close되어 다시 생성하게 되었습니다.
해당 이슈에 관련해서는 디스코드 방에 재공유할 예정입니다.
=> [fix] FAQ 페이지네이션 및 질문 열기 시 스크롤 이동 버그 수정

apps/client/src/app/check-result/layout.tsx, apps/client/src/hooks/api/test-result/index.ts, apps/client/src/hooks/api/test-result/useGetFinalTestResult.ts, apps/client/src/hooks/api/test-result/useGetFirstTestResult.ts, apps/client/src/pageContainer/CheckFinalResultPage/index.tsx, apps/client/src/pageContainer/CheckFirstResultPage/index.tsx, packages/api/src/apis/test-result/getFinalTestResult.ts, packages/api/src/apis/test-result/getFirstTestResult.ts, packages/api/src/libs/queryKeys.ts, packages/api/src/libs/requestUrlController.ts, packages/shared/src/constants/regex.ts, packages/shared/src/schemas/birthSchema.ts, packages/shared/src/schemas/checkFinalTestResultSchema.ts, packages/shared/src/schemas/checkFirstTestResultSchema.ts, packages/shared/src/schemas/index.ts, packages/shared/src/utils/formatBirth.ts, packages/shared/src/utils/index.ts, packages/types/src/check-result.ts, packages/types/src/index.ts
사용자가 로그인 없이, 이름 + 생년월일(8자) + 전화번호로 조회하도록 변경했습니다
* 수험번호 + 부모님/선생님 전화번호로 조회 ->  이름 + 생년월일(8자) + 전화번호로 조회
* 생년월일 입력을 select로 설정
* `/check-result`에 접근시 나왔던 로그인 알림 모달창 삭제
* 합불 조회 api 엔드포인트 교체 & 쿼리스트링 수정
* 생년월일(8자) 스키마 생성
* 1차, 최종 조회 폼 스키마 변경
https://github.com/user-attachments/assets/25d1d697-8aa3-4061-adc8-e0a7db3f576d
빠른 개발을 위해 ui적인 부분은 임의로 지정해뒀습니다
추후에 디자인이 제공된다면 수정하겠습니다
=> [feat] 1차, 최종 합격자 조회 방법 변경

.github/workflows/regular-deploy.yml
정기베포 github action의 기간을 수정했습니다
기존에 사용하던 `cron: "0 0 */14 * *"` 설정은 매월 기준으로 주기가 초기화되어, 14일마다 실행되길 원했던 의도와 달리 매월 1일, 15일, 29일에 동작했습니다.
이에 매달 1일과 15일에만 Action이 실행되도록 cron 값을 수정하였습니다.
=> [fix]정기베포 기간 수정

apps/admin/src/app/callback/page.tsx, apps/admin/src/pageContainer/CallbackPage/index.tsx, apps/admin/src/pageContainer/index.ts, apps/client/src/app/callback/page.tsx, apps/client/src/pageContainer/CallbackPage/index.tsx, apps/client/src/pageContainer/index.ts, packages/api/src/hooks/api/auth/index.ts, packages/api/src/hooks/api/auth/useOAuthLogin.ts, packages/api/src/libs/requestUrlController.ts, packages/shared/src/components/ui/LoginButton/index.tsx
> OAuth 로그인 후 바로 BE URL로 리다이렉트되어 인증 처리 후 FE로 다시 리다이렉트 해주는 방식인데 만약 인증 처리 중 오류가 발생할 경우 화이트라벨 에러페이지가 사용자에게 노출되어 FE에서 이를 관리할 수가 없습니다.
위와 같은 문제로 인해, 프론트엔드에서 직접 OAuth 인증 요청을 수행한 후, 발급받은 Authorization Code를 백엔드로 REST API 형태로 전달하는 방식으로 변경하였습니다.
- 로그인 요청 엔드포인트 변경
- useOAuthLogin 훅 제작
- 로그인 버튼 리팩토링
- client, admin callback 페이지 제작
https://www.notion.so/OAuth-Flow-22b3f725618580899444fe35740f3e86?source=copy_link
사용자가 로그인 버튼을 클릭하면 프론트엔드에서 백엔드의 OAuth 인증 엔드포인트(`/auth/v3/auth/authorization/{provider}`)로 리다이렉트됩니다. 백엔드는 OAuth 제공자와 전체 인증 과정을 처리하며, Authorization Code 수신부터 Access Token 교환, 사용자 정보 처리까지 모든 과정을 담당합니다. 인증 성공 시 프론트엔드로 리다이렉트하지만, 실패 시에는 사용자에게 직접 화이트라벨 에러 페이지를 표시합니다.
사용자가 로그인 버튼을 클릭하면 프론트엔드에서 OAuth 제공자와 직접 통신하여 인증 페이지로 이동합니다. 사용자 인증 완료 후 OAuth 제공자로부터 Authorization Code를 직접 수신하고, 이를 백엔드 API(POST, …
=> [refactor] OAuth flow 변경

apps/client/src/pageContainer/PrintPage/index.tsx
> printPage 예체능 점수 학기별 순서 오류 수정
- printPage에서 예체능 교과 점수가 학기 구분 없이 순서대로만 출력되는 문제가 있었습니다.
- 졸업 예정자와 자유학년제 여부를 고려하지 않아, 실제 학기별 성적 배치가 잘못 표시되었습니다.
(졸업 예정 + 자유학년제 :  2-1학기부터 예체능 성적 배치 해야하지만 1-1학기부터 배치되었음)
- [관련 노션](https://www.notion.so/print-24f3f72561858054ba4edfceab684668?source=copy_link)
성적 점수는 예시이니 참고만 해주세요
[수정 전]
[수정 후]
- 졸업 예정 + 자유학년제 → 2-1부터 출력 확인
- 졸업 예정 + 일반 → 1-1부터 출력 확인
- 졸업자 → 기존 순서 유지(2-1부터 출력) 확인
=> [fix] printPage 예체능 점수 학기별 순서 오류 수정

packages/shared/src/components/form/FreeSemesterForm/index.tsx
step간 이동시 자유학기제 유지되지 않던 문제를 수정했습니다
https://github.com/user-attachments/assets/b10756bb-74e4-4f3f-b664-c0bc1b637fcd
step 이동시 UI상으론 자유학기제가 선택되어 있는것 처럼 보였지만
실제론 `null`이 아닌 빈 배열이 들어가있어, 
성적계산버튼과 원서최종제출 버튼이 활성화 되지 않습니다
=> [fix] step간 이동시 자유학기제 유지

apps/client/src/components/Footer/index.tsx, apps/client/src/components/MainPage/Section1/index.tsx, apps/client/src/components/MainPage/Section2/index.tsx, apps/client/src/components/MainPage/Section3/index.tsx, apps/client/src/components/MainPage/Section4/index.tsx, apps/client/src/components/MainPage/Section5/index.tsx
디자인과 다르게 되어있던 메인페이지 요소들을 디자인에 맞게 수정했습니다.
- 메인 페이지 폰트 사이즈, 갭 등 수정
- 푸터 폰트 사이즈 조정
피그마 디자인과 다른 부분이 작업한 영역 외에도 많았지만, 지금 당장 모두 수정하기에는 시간이 다소 걸릴 것 같아 우선 눈에 가장 잘 띄는 부분만 수정했습니다.
=> [feat] 메인페이지, 헤더, 푸터 사소한 디자인 조정

apps/client/src/pageContainer/CheckFinalResultPage/index.tsx, apps/client/src/pageContainer/CheckFirstResultPage/index.tsx
조회 결과가 조회된 사람 없음 모달과 함께 중복으로 표시되던 현상을 수정했습니다
`handleFormSubmit` 함수 내에서 `setQueryParams`를 호출하여 `queryParams`의 값이 변경되는데
모달 여부를 관리하는 useEffect의 조건에 `queryParams`가 조건으로 들어가 있어
```tsx
useEffect(() => {
if (data) {
console.log(1, data, error, queryParams)
setName(data.name);
setResultInfo({
decidedMajor: data.decidedMajor,
firstTestPassYn: 'YES',
secondTestPassYn: data.secondTestPassYn,
});
setIsDialog(true);
} else if (
(error || data === undefined) &&
queryParams &&
queryParams.name !== '' &&
queryParams.birth !== '' &&
queryParams.phoneNumber !== ''
) {
console.log(2, data, error, queryParams)
setIsFailRequestDialog(true);
}
}, [data, error, queryParams]);
```
queryParams가 변경되어 useEffect가 호출이 되지만 아직 data는 undefined로 아직 오지 않아 ` setIsFailRequestDialog(true);`이 실행되어 `조회된 사람 없음` 모달이 발생하고
<br /> …
=> [fix] 합격자 조회시 중복 모달

apps/client/src/pageContainer/SignUpPage/index.tsx
회원가입 성공 후에도 헤더에 '회원가입을 진행해주세요'라는 문구가 표시되는 문제가 있었습니다. 원인을 확인해 보니 useGetMyAuthInfo, useGetMyMemberInfo 훅에 staleTime이 설정되어 있어, refetch를 호출해도 이전에 불러온 데이터가 그대로 반환되는 것이었습니다. 이를 해결하기 위해 invalidateQueries를 사용해 staleTime과 관계없이 쿼리 데이터를 강제로 오래된(stale) 상태로 변경하는 방식으로 수정했습니다.
- refetch 함수들을 queryClient.invalidateQueries로 변경
=> [refactor] 회원가입 성공 후 쿼리 캐시 무효화 방식으로 개선

packages/shared/src/components/register/Step4Register/index.tsx
> GED 평균 점수 입력란 숫자 처리 개선을 위해  `0/NaN` 방지 및 한글/영어 입력 차단 작업 진행했습니다.
* GED 평균 점수 `Input`에서 한글/영어 입력을 실시간으로 제거하도록 수정
* 빈 문자열, 0 또는 잘못된 값(NaN) 입력 시 내부 state가 `undefined`가 되도록 `setValueAs` 처리
* 기존 방식에서는 화면에 입력되지 않아도 내부 값이 남아 zod 유효성 검사가 꼬이는 문제 발생
* 새 방식은 화면과 내부 상태가 항상 일치하도록 개선하여, GED `Input`이 빈값으로 안전하게 유지되도록 수정
=> [fix] GED 평균 점수 입력란 숫자 처리 개선 

.github/workflows/stage-cd.yml, .github/workflows/stage-ci.yml
`NEXT_PUBLIC_STAGE`를 추가했습니다
stage환경이 검색엔진에 노출되는 현상이 발생했습니다
```tsx
{process.env.NEXT_PUBLIC_STAGE === 'stage' && (
<>
<meta name="robots" content="noindex, nofollow" />
<meta name="msvalidate.01" content="14471419A8701E4145F89E3ADCCFB1D6" />
</>
)}
```
해당부분에서 `NEXT_PUBLIC_STAGE`관련 설정이 정상적으로 적용되지 않는 것 같아, workflows에 `NEXT_PUBLIC_STAGE`를 추가했습니다
repogitory secrets에 `NEXT_PUBLIC_STAGE` 추가
=> [ci/cd] stage env추가

apps/client/src/components/Header/index.tsx
> header 반응형 수정 작업 진행했습니다.
> [257](https://github.com/themoment-team/hellogsm-front-24/pull/257) 해당 PR에서 디자인과 통일하기 위해 `'w-[10rem]'` 속성을 삭제하자 '내 정보 페이지' 텍스트가 줄바꿈되는 현상이 발생했습니다.
이를 해결하기 위해 `gap` 사이즈를 줄이고, `DropdownMenu`의 위치를 조정했습니다.
=> [style] Header 간격 및 드롭다운 메뉴 위치 조정

apps/client/src/components/PrintPage/PrintButton/index.tsx
'인쇄하기' 버튼이 햄버거 메뉴 위로 올라오는 문제가 있어서 버튼의 z-index 조정했습니다
'인쇄하기' 버튼 z-index 조정
https://github.com/user-attachments/assets/04b97162-75e4-4e02-92de-ec3088f5208d
=> [fix] 인쇄 버튼 z-index 조정

apps/client/src/components/PrintPage/ArtsPhysicalTable/index.tsx, apps/client/src/components/PrintPage/GeneralSubjectsTable/index.tsx
>  '성취도/평어' 텍스트를 '성취도'로 수정하였습니다.
=> [fix] '성취도/평어' 텍스트를 '성취도'로 수정

packages/shared/src/schemas/step4Schema.ts
추가 과목 중복 문제를 방지할수 있도록 zod schema를 수정하였습니다
- zod schema 수정
사용자가 원서를 작성하면서 추가 과목 이름이 중복이 되는 경우에는 진짜로 중복이 된지 모르는 상황 밖에 없다고 생각이 드는데 피드백이 없이 단순히 버튼 비활성화가 된다면 사용자 경험이 떨어질것 같다고 생각합니다.
하지만 현재 원서 작성 기능은 입력값이 입력되야지만 다음, 제출 버튼이 활성화 되는 식이라 버튼을 눌렀을때 alert, toast로 피드백을 줄수 있는 상황이 아닙니다. 이 부분을 개선할수 있는 방법을 고민해보면 좋을것 같습니다
=> [feat] 추가 과목 중복 방지

apps/client/src/components/MainPage/Section2/index.tsx, apps/client/src/components/MainPage/Section3/index.tsx
> https://github.com/themoment-team/hellogsm-front-25/pull/277 해당 pr 에서 승재 선배님께서 말씀해주신 것처럼 
2026년 1월에 아직 2027년도 모집 계획이 fix되지 않았을 때 `NEXT_YAER`을 사용하여 보여준다면, 사용자에게 혼란을 줄 것 같아 
이를 없애기 위해 `NEXT_YAER` 을 사용하는 것이 아닌 `2026`으로 재변경하였습니다
=> [fix] 모집 안내 연도 수정

packages/shared/src/constants/subject.ts
일반 교과 과목에 '정보'를 추가하고 입학전형요강에 있는 원서 양식에 맞게 과목 순서를 변경 했습니다.
- 일반 교과 과목에 '정보'를 추가
- 입학전형요강에 있는 원서 양식에 맞게 과목 순서 변경
=> [feat] 일반 교과 과목 추가 및 순서 변경

apps/client/src/components/OneseoStatus/index.tsx
검정고시 지원자의 원서에서 교과성적 소계, 비교과 성적 소계가 잘 못 표기되던 문제 해결했습니다.
- 교과성적 소계, 비교과 성적 소계가 잘 못 표기되던 문제 해결
=> [fix] 검정고시 지원자 잘못된 점수 표시 수정

apps/client/src/pageContainer/CalculatePage/index.tsx, apps/client/src/pageContainer/CheckResultPage/index.tsx
모의 성적 계산에서 팝업 버튼이 간헐적으로 클릭되지 않던 이슈 해결했습니다
- asChild 프롭 사용하여 모의 성적 계산에서 팝업 버튼이 간헐적으로 클릭되지 않던 이슈 해결
=> [fix] AlertDialog 버튼 간헐적 클릭 문제 해결

apps/client/src/components/OneseoStatus/index.tsx
선생님 요구사항대로 원서에서 '지역명' 라벨 텍스트를 '주소'로 변경했습니다.
원서에서 '지역명' 라벨 텍스트를 '주소'로 변경
=> [fix] 원서 지역명 라벨 텍스트 수정

apps/client/src/components/PrintPage/OneseoStatus/index.tsx
> 교과성적 테이블에 검정고시 평균 점수 표시 작업했습니다.
- 검정고시 평균 점수 표시
- ~~검정고시일 경우, `소계` -> `환산점` 으로 표기~~
- 성적 셀 너비 통일(3rem)
**[변경 전]**
**[변경 후]**
=> [fix] 검정고시 평균 점수 표시

apps/client/src/pageContainer/CalculatePage/index.tsx
> 이전 PR #296 에서 누락된 `CalculatePage`에서 `defaultValues.liberalSystem`을 `자유학기제(FREE_SEMESTER)`로 변경하였습니다.
=> [fix] CalculatePage defaultValues.liberalSystem을 FREE_SEMESTER로 변경

.github/workflows/prod-cd.yml, .github/workflows/prod-ci.yml, .github/workflows/stage-cd.yml, .github/workflows/stage-ci.yml
기존 HelloGSM FE의 CI/CD 파이프라인에서 환경변수를 `--build-arg`로 개별적으로 주입하는 방식을 사용하고 있었습니다. 환경변수 수가 증가함에 따라 이러한 방식은 관리 복잡성을 높이고 스크립트 가독성을 저해하는 문제가 발생했습니다. 이를 해결하기 위해 `env` secret을 활용한 통합 환경변수 주입 방식으로 개선하였습니다.
기존에는 각 환경변수를 개별적으로 `--build-arg`를 통해 주입하였습니다.
```shell
- name: Docker Client build
run: |
docker build \
--build-arg NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_PROD_API_BASE_URL }} \
--build-arg NEXT_PUBLIC_CHANNEL_IO_KEY=${{ secrets.NEXT_PUBLIC_CHANNEL_IO_KEY }} \
--build-arg NEXT_PUBLIC_IMAGE_URL=${{ secrets.NEXT_PUBLIC_IMAGE_URL }} \
--build-arg NEXT_PUBLIC_SHOW_LOGIN_MODAL_FF=${{ secrets.NEXT_PUBLIC_SHOW_LOGIN_MODAL_FF }} \
--build-arg NEXT_PUBLIC_NEIS_API_KEY=${{ secrets.NEXT_PUBLIC_NEIS_API_KEY }} \
--build-arg NEXT_PUBLIC_NOTION_FAQ_DATABASE_ID=${{ …
```
=> [refactor] CI/CD 시 환경변수 주입 리팩터링

apps/client/src/components/PassResultDialog/index.tsx
> 선생님의 요청에 따라, 신입생 전형요강에 나와있는 문구와 일치시키기 위해 
`1차 서류 전형` → `1차 전형`으로 변경하였습니다.
[신입생 전형요강 6p 참고]
[참고 노션 바로 가기](https://www.notion.so/25-09-25-2793f72561858064b147f16cd18d4069?source=copy_link)
=> fix: 1차 전형 메시지에서 '서류' 단어 제거

packages/shared/src/components/register/Step1Register/index.tsx
> 사용자가 집 주소 검색 시 "서울", "광주" 등 축약형 주소가 아닌 "서울특별시", "광주광역시" 등 정식명칭으로 표시되도록 개선했습니다.
> 기존에는 "서울", "광주" 등 축약형이 표시되어 관리자가 수작업으로 "서울특별시", "광주광역시" 등으로 변경해야 했습니다. 이를 자동화하여 데이터 일관성과 관리 효율성을 높였습니다.
[지원자등록양식.xlsx](https://github.com/user-attachments/files/22551567/_20250909_101311.xlsx)
- `handleDaumPostCodePopupComplete` 함수에 주소 변환 로직 추가
- 17개 시/도에 대한 정식명칭 매핑 처리
- 2024년 행정구역 개편 반영 (강원특별자치도, 전북특별자치도)
- 정규식 체인을 활용한 효율적인 문자열 변환 구현
=> [feat] 주소 정식명칭 변환 기능 추가

packages/shared/src/components/modal/AdminModals/index.tsx
어드민 페이지에서 1, 2차 결과 발표 시에 성공/실패 토스트 알림을 추가했습니다.
- 1, 2차 결과 발표 시 토스트 알림 추가
테스트를 진행해보지 못 했습니다.
=> [feat] 1, 2차 결과 발표 시 토스트 알림 추가

apps/admin/src/components/ApplicantTH/index.tsx, apps/admin/src/components/ApplicantTR/index.tsx
선생님 요구사항에 따라 컬럼명을 '지원자 정보'에서 '성명'으로 변경하고, 이름만 표시되도록 수정했습니다.
- 컬럼명을 '지원자 정보' -> '성명'으로 변경
- 전화번호는 제외하고 이름만 표시되도록 수정
=> [fix] 지원자 목록 테이블 표시 정보 수정

apps/client/src/pageContainer/SignUpPage/index.tsx
번호 인증 시 3분 타이머가 종료된 후에도 전화번호 입력란이 비활성화된 문제가 있었는데, 타이머 만료 시 사용자가 휴대폰 번호를 다시 입력할 수 있도록 수정했습니다.
번호 인증 타이머 만료 시 휴대폰 번호 재입력 허용
=> [fix] 번호 인증 타이머 만료 시 휴대폰 번호 재입력 허용
